name: Deploy Frontend to S3

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build

    - name: Deploy to S3
      run: aws s3 sync ./out s3://uconnect-nextjs-app-bucket --acl public-read --delete
